name: trokis
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  intl:
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  timeago:
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.10
  mime_type: ^1.0.1
  internet_connection_checker_plus: ^2.7.0
  flutter_otp_text_field: ^1.4.0+2
  flutter_widget_from_html:
  video_player: ^2.9.2
  socket_io_client: ^3.0.2
  dotted_border: ^2.1.0
  http: ^1.2.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  logger: ^2.5.0
  google_maps_flutter: ^2.10.0
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  file_picker: ^8.1.7

dev_dependencies:
  flutter_gen_runner: null
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/global/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true
    #===========>>>>>>>>>> Flutter Gen Code ==============>>>>>>>>>>>
    # dart pub global activate flutter_gen
    # flutter pub run build_runner build --delete-conflicting-outputs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/flag/
    - assets/video/.
    - assets/images/map_marker.png
    - .env



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
        - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

